#!/usr/bin/env python3

# Copyright (c) 2016, Robert Escriva, Cornell University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Consus nor the names of its contributors may be
#       used to endorse or promote products derived from this software without
#       specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import os
import os.path
import stat

def lines():
    for line in open('Makefile.am'):
        yield 'file', line
        x = line.split('+=')
        if len(x) != 2: continue
        g = x[1].strip()
        if not g.endswith('.gremlin'): continue
        if g.endswith('.valgrind.gremlin'): continue
        if not os.path.exists(g): continue
        v = g[:-len('.gremlin')] + '.valgrind.gremlin'
        f = open(v, 'w')
        f.write('#!/usr/bin/env gremlin\n')
        f.write("env GREMLIN_PREFIX 'libtool --mode=execute valgrind --tool=memcheck --trace-children=yes --error-exitcode=127 --leak-check=full --gen-suppressions=all --suppressions=\"${CONSUS_SRCDIR}/consus.supp\"'\n")
        f.write('include ' + os.path.basename(g) + '\n')
        f.flush()
        f.close()
        os.chmod(v, stat.S_IRWXU)
        yield 'auto', (x[0] + '+= ' + v + '\n')

prev = None
fout = open('Makefile.am.tmp', 'w')
for line in lines():
    if prev is None or prev[0] != 'auto' or prev[1] != line[1]:
        fout.write(line[1])
    prev = line
fout.flush()
fout.close
os.rename('Makefile.am.tmp', 'Makefile.am')
